### ISSUE TITLE
ANT 2 Circuit Error

### ISSUE THREAD

**Issue by nicopace** [libremesh/librerouter#11]
L/C high pass filter circuit is incorrect for ANT 2

Circuit is correct for ANT3 (L25/C165) or ANT1 (L31/C278)

See Issue 13 also.

**Comment by tgillett** [comment]
Investigated by Edwin and identified schematic/component differences for Ant 2. 
Moved to Phase 2 testing for checking in board re-design.

**Comment by dragino** [comment]
We will look into it in the re-design board.

**Comment by spiccinini** [comment]
Fixed in phase2
