### ISSUE TITLE
Board Mounting

### ISSUE THREAD

**Issue by nicopace** [libremesh/librerouter#12]
There are limited mounting holes which correspond to the mounting points in the proposed enclosure.
But it is needs to be looked at to ensure that the board will be mechanically secure.

Also, possibly worthwhile to provide additional holes in each corner and middle of the board so that it can be easily mounted in simple box enclosures.

**Comment by dragino** [comment]
The new 9558 Mega Board will have more mounting holes.

**Comment by spiccinini** [comment]
Mega board v1.1 has 7 mounting holes and some other usable holes.
