### ISSUE TITLE
Board hangs after reboot.

### ISSUE THREAD

**Issue by nicopace** [libremesh/librerouter#3]
Reboot without power-cycling doesn't work.

**Comment by dangowrt** [comment]
sounds like the SPI chip doesn't get the reset and/or is switched
to stateful 4-byte-address mode (which should be avoided in spi-nor).
Once I get the board to do anything I can check whether JTAG works
after reboot and figure out where the boot hands.

**Comment by dangowrt** [comment]
related to #19

**Comment by tgillett** [comment]
Addressed by Daniel Golle's work on the SPI chip.
May require a different chip type.
Moved to Phase 2 testing to check design solution.

**Comment by spiccinini** [comment]
We have agreed to change the specification of the 2nd prototype to 16MB.

**Comment by dragino** [comment]
While using the 32MB flash chip w25q256fv, if we connect the current pin1(HOLD) and pin3(/RESET) together, since pin1 is connected to SYS_RST_L . while the QCA9558 reboot, it will send a low to SYS_RST_L so to reset the flash. This can fix this reset issue.

**Comment by spiccinini** [comment]
This is fixed in phase2 (MegaBoard v1.1 / Core v0.2)
