### ISSUE TITLE
Hardware Reset Operation: Watchdog

### ISSUE THREAD

**Issue by nicopace** [libremesh/librerouter#4]
GPIO 2 connected to ATTINY hardware reset chip (schematic pp 6)

GPIO2, 3 Designated as EJTAG_TDO, EJTAG_TMS

GPIO2, 3 connected to WAKE_L_0, WAKE_L_1 line on PCIe connectors. (schematic pp15)

Is there a conflict on GPIO 2??

**Comment by tgillett** [comment]
GPIOs 2 and 3 are working correctly with updated firmware.

Phase 1 testing of ATTINY hardware reset can be undertaken.

**Comment by spiccinini** [comment]
Watchdog circuit is working in phase 2 (MegaBoard v1.1 Core board v0.2). Details in https://github.com/spiccinini/librerouter-watchdog
